import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Navbar } from './components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-screen w-screen overflow-x-hidden flex flex-col justify-center items-center bg-gray-500`}
      >
        <Navbar />
        {children}
        <footer className="text-right px-8 py-2 text-xs bg-green">
          © {new Date().getFullYear()} K@to
        </footer>
      </body>
    </html>
  );
}
